# Dating app

In [1]:
#import the necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#upload the csv files

users_inst = pd.read_csv('./raw_data/lovoo_v3_users_instances.csv')
users_api_res = pd.read_csv('./raw_data/lovoo_v3_users_api-results.csv')
users_inter = pd.read_csv('./raw_data/interests-of-users-by-age.csv')

In [7]:
users_api_res.head()

,gender,genderLooking,age,name,counts_details,counts_pictures,counts_profileVisits,counts_kisses,counts_fans,counts_g,...,shareProfileEnabled,lastOnlineDate,lastOnlineTime,birthd,crypt,freetext,whazzup,pictureId,userId,isSystemProfile
0,F,M,25,daeni,1.00,4,8279,239,0,3,...,1,2015-04-25T20:43:26Z,1.429995e+09,0,NaN,Nur tote Fisch schwimmen mit dem Strom,Nur tote fische schwimmen mit dem strom,4e3842f79b70e7ea57000064,55303fc3160ba0eb728b4575,NaN
1,F,M,22,italiana 92,0.85,5,663,13,0,0,...,1,2015-04-26T09:19:35Z,1.430040e+09,0,NaN,NaN,Primaveraaa<3,4e3d34bf5d2bce7b160006a3,552e7b61c66da10d1e8b4c82,NaN
2,F,M,21,Lauraaa,0.00,4,1369,88,0,2,...,1,2015-04-06T14:24:07Z,1.428330e+09,0,NaN,NaN,NaN,4ec96c090dc82cb25d00000a,54a584ecc56da128638b4674,NaN
3,F,none,20,Qqkwmdowlo,0.12,3,22187,1015,2,3,...,1,2015-04-07T11:21:01Z,1.428406e+09,0,NaN,NaN,Je pense donc je suis. Instagram quedev,4eef8b81ebf2c8f64000000c,54c92738076ea1b5338b4735,NaN
4,F,M,21,schaessie {3,0.15,12,35262,1413,9,12,...,1,2015-04-06T14:25:20Z,1.428330e+09,0,NaN,NaN,Instagram: JESSSIESCH,4ef3cc5aa9d0b3d07d000017,54e1a6f6c76da135748b4a3a,NaN

In [3]:
users_inst

,gender,age,name,counts_pictures,counts_profileVisits,counts_kisses,flirtInterests_chat,flirtInterests_friends,flirtInterests_date,connectedToFacebook,...,hasBirthday,highlighted,distance,locked,mobile,online,whazzup,pictureId,userId,isSystemProfile
0,F,25,daeni,4,8279,239,True,True,True,False,...,False,False,175.000000,False,True,False,Nur tote fische schwimmen mit dem strom,4e3842f79b70e7ea57000064,55303fc3160ba0eb728b4575,False
1,F,22,italiana 92,5,663,13,True,True,True,False,...,False,False,138.000000,False,True,False,Primaveraaa<3,4e3d34bf5d2bce7b160006a3,552e7b61c66da10d1e8b4c82,False
2,F,20,Qqkwmdowlo,3,22187,1015,True,True,False,False,...,False,False,77.300003,False,False,False,Je pense donc je suis. Instagram quedev,4eef8b81ebf2c8f64000000c,54c92738076ea1b5338b4735,False
3,F,24,Baby dee,18,7339,180,True,False,True,False,...,False,False,194.000000,False,True,True,Wicked Wonderland💕❤️,4ef9434cca61bece6a000002,54f2b4ce0b6ea1177e8b4d18,False
4,F,24,Anna,13,18672,492,False,True,False,False,...,False,False,318.000000,False,True,True,💚 ✅ Instagram : anna_lem0n,4f10cbc1883fa97a5f000015,54ecbb39170ba08b488b4aa5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,F,20,Ma**e,8,1101,46,True,True,True,False,...,False,False,0.000000,False,False,False,Marie ॐ 🎉Goa. Facebook:Ma...,CRYVOrW7zgSV+NPGili4nZeREmQ0rAAXCZunTXp9KRLat1...,d5a7edbcb59fcb092871bdcde7f142ca,False
2915,F,23,Eni**n,8,8681,141,True,True,True,False,...,False,False,0.000000,True,True,True,ruhig shriebe😉. bissä ni,CRYohLWFV8BkxZIvOom42Cwo3ysdViv+oTosUAOQkLKHTM...,e532a6060fe4e5902c66086d905a9d53,False
2916,F,23,Eni**n,8,8682,141,True,True,True,False,...,False,False,0.000000,True,True,False,ruhig shriebe😉. bissä ni,CRYz85gM+yTETN5FonrExXNHyDuwarWygCPnUrwnan7Uet...,e532a6060fe4e5902c66086d905a9d53,False
2917,F,23,Eni**n,8,8702,142,True,True,True,False,...,False,False,0.000000,False,True,True,ruhig shriebe😉. bissä ni,CRYsH4q+r4fCkC8+leJqDdJQtbUNQGCyqLx36aDsEzC5b9...,e532a6060fe4e5902c66086d905a9d53,False
2918,F,23,Eni**n,9,8904,143,True,True,True,False,...,False,False,0.000000,False,True,False,ruhig shriebe😉. bissä ni,CRYbrX0C8ToNrsDqLPf+kLsCSuDY0TOhyKSo3Phw98sbl+...,dc186f3855343c9f096c484f6d363aac,False